# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcfrmMain(wx.Frame):
#!XRCED:begin-block:xrcfrmMain.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcfrmMain.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "frmMain")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.txtSqlDb = xrc.XRCCTRL(self, "txtSqlDb")
        self.btOpenSqlDb = xrc.XRCCTRL(self, "btOpenSqlDb")
        self.txtSqlFile = xrc.XRCCTRL(self, "txtSqlFile")
        self.btOpenSqlFile = xrc.XRCCTRL(self, "btOpenSqlFile")
        self.chkMonitorFile = xrc.XRCCTRL(self, "chkMonitorFile")
        self.btExecuteFile = xrc.XRCCTRL(self, "btExecuteFile")
        self.btCommit = xrc.XRCCTRL(self, "btCommit")
        self.lstResults = xrc.XRCCTRL(self, "lstResults")
        self.txtMessages = xrc.XRCCTRL(self, "txtMessages")

        self.Bind(wx.EVT_CLOSE, self.OnClose)

#!XRCED:begin-block:xrcfrmMain.OnClose
    def OnClose(self, evt):
        # Replace with event handler code
        print "OnClose()"
#!XRCED:end-block:xrcfrmMain.OnClose        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    sqbrowser_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="frmMain">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxSplitterWindow">
          <object class="wxPanel">
            <object class="wxBoxSizer">
              <orient>wxVERTICAL</orient>
              <object class="sizeritem">
                <object class="wxFlexGridSizer">
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>SQL DB:</label>
                      <style>wxALIGN_RIGHT</style>
                    </object>
                    <flag>wxGROW</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="txtSqlDb">
                      <style>wxNO_BORDER|wxTE_READONLY</style>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <option>1</option>
                    <flag>wxEXPAND</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btOpenSqlDb">
                      <label>Connect</label>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>SQL:</label>
                      <style>wxALIGN_RIGHT</style>
                    </object>
                    <flag>wxEXPAND</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="txtSqlFile">
                      <style>wxNO_BORDER|wxTE_READONLY</style>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <option>1</option>
                    <flag>wxEXPAND</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btOpenSqlFile">
                      <label>Select</label>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                  </object>
                  <cols>3</cols>
                  <rows>2</rows>
                  <vgap>3</vgap>
                  <hgap>3</hgap>
                  <growablecols>1</growablecols>
                </object>
                <flag>wxALL|wxEXPAND</flag>
                <border>3</border>
              </object>
              <object class="sizeritem">
                <object class="wxBoxSizer">
                  <object class="sizeritem">
                    <object class="wxCheckBox" name="chkMonitorFile">
                      <label>Autorun SQL File</label>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                  </object>
                  <object class="spacer">
                    <size>10,0</size>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btExecuteFile">
                      <label>Execute SQL</label>
                      <default>1</default>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxBoxSizer">
                      <object class="sizeritem">
                        <object class="wxButton" name="btCommit">
                          <label>Commit</label>
                          <XRCED>
                            <assign_var>1</assign_var>
                          </XRCED>
                        </object>
                        <flag>wxALIGN_RIGHT</flag>
                      </object>
                      <orient>wxVERTICAL</orient>
                    </object>
                    <option>1</option>
                    <flag>wxEXPAND</flag>
                  </object>
                  <orient>wxHORIZONTAL</orient>
                  <object class="spacer">
                    <size>100,0</size>
                  </object>
                </object>
                <flag>wxEXPAND</flag>
              </object>
            </object>
          </object>
          <object class="wxSplitterWindow">
            <object class="wxPanel">
              <object class="wxBoxSizer">
                <orient>wxVERTICAL</orient>
                <object class="sizeritem">
                  <object class="wxListCtrl" name="lstResults">
                    <style>wxLC_REPORT|wxLC_HRULES|wxLC_VRULES|wxLC_NO_SORT_HEADER</style>
                    <XRCED>
                      <assign_var>1</assign_var>
                    </XRCED>
                  </object>
                  <option>1</option>
                  <flag>wxALL|wxEXPAND</flag>
                  <border>3</border>
                </object>
              
            </object>
            </object>
            <object class="wxPanel">
              <object class="wxBoxSizer">
                <object class="sizeritem">
                  <object class="wxTextCtrl" name="txtMessages">
                    <size>-1,80</size>
                    <style>wxTE_AUTO_SCROLL|wxTE_MULTILINE|wxTE_READONLY|wxHSCROLL|wxTE_RICH|wxTE_RICH2</style>
                    <XRCED>
                      <assign_var>1</assign_var>
                    </XRCED>
                  </object>
                  <option>1</option>
                  <flag>wxEXPAND</flag>
                </object>
                <orient>wxVERTICAL</orient>
              </object>
            </object>
            <orientation>horizontal</orientation>
            <minsize>100</minsize>
            <style>wxNO_BORDER</style>
          </object>
          <orientation>horizontal</orientation>
          <sashpos>80</sashpos>
          <minsize>80</minsize>
          <style>wxSP_PERMIT_UNSPLIT</style>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>3</border>
      </object>
    </object>
    <title>SQBrowser</title>
    <centered>1</centered>
    <exstyle></exstyle>
    <XRCED>
      <events>EVT_CLOSE</events>
    </XRCED>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/sqbrowser/sqbrowser_xrc', sqbrowser_xrc)
    __res.Load('memory:XRC/sqbrowser/sqbrowser_xrc')

